cask "ghostty"
brew "neovim"
brew "tmux"
brew "oh-my-posh"
brew "lazygit"
brew "uv"
brew "node"
brew "pnpm"
cask "visual-studio-code"
cask "font-jetbrains-mono-nerd-font"
cask "microsoft-edge"
cask "microsoft-teams"
cask "microsoft-word"
cask "microsoft-excel"
cask "microsoft-powerpoint"

